"""
HackOverflow Expert Agent — answers coding questions from the Router.
Receives Question, generates solution/explanation, sends Answer back to Router.
"""
import os
from dotenv import load_dotenv
from uagents import Agent, Context, Protocol
from models import Question, Answer

load_dotenv()

EXPERT_SEED = os.getenv("AGENT_EXPERT_SEED", "hackoverflow-expert-agent-seed-phrase")
PORT = int(os.getenv("AGENT_PORT_EXPERT", "8004"))

expert = Agent(
    name="hackoverflow_expert",
    seed=EXPERT_SEED,
    port=PORT,
    mailbox=True,
    publish_agent_details=True,
)

qa_proto = Protocol(name="hackoverflow_qa", version="1.0.0")


def _generate_solution(msg: Question) -> Answer:
    """Generate a solution for the question (demo: template; plug in LLM/code analysis later)."""
    solution = (
        f"Suggested fix for {msg.language} error:\n"
        f"1. Check: {msg.error_message[:200]}.\n"
        f"2. Review the stack trace and ensure imports/env match.\n"
        f"3. Try a minimal repro and add logging."
    )
    code_snippet = (
        "# Minimal fix pattern\n"
        "try:\n"
        "    # your code here\n"
        "except Exception as e:\n"
        "    import traceback\n"
        "    traceback.print_exc()\n"
    )
    return Answer(
        question_id=msg.question_id,
        solution=solution,
        explanation="Generated by HackOverflow expert. Run tests to verify.",
        code_snippet=code_snippet,
        verified=False,
    )


@qa_proto.on_message(Question)
async def handle_question(ctx: Context, sender: str, msg: Question):
    ctx.logger.info(f"Expert received Question {msg.question_id} from {sender}")
    answer = _generate_solution(msg)
    await ctx.send(sender, answer)


expert.include(qa_proto)

if __name__ == "__main__":
    expert.run()
